# Templates de secrets (NE PAS COMMITTER les valeurs r√©elles)
apiVersion: v1
kind: Secret
metadata:
  name: dynatrace-api-token
  namespace: dynatrace
type: Opaque
stringData:
  apiToken: "<REDACTED>"

---
apiVersion: v1
kind: Secret
metadata:
  name: dynatrace-data-ingest-token
  namespace: dynatrace
type: Opaque
stringData:
  dataIngestToken: "<REDACTED>"
